feat(srat): ✨ update SRAT installation method and enhance update options
* Changed the installation method for SRAT from individual downloads to a zip file extraction.
* Added support for `localfile` option in `update_srat_onstart` configuration.
* Improved error handling and logging during the update process.
* Updated version in `config.yaml` to 12.5.0-ns2.alpha16.

diff --git a/sambanas2/rootfs/etc/s6-overlay/s6-rc.d/init-srat/run b/sambanas2/rootfs/etc/s6-overlay/s6-rc.d/init-srat/run
--- a/sambanas2/rootfs/etc/s6-overlay/s6-rc.d/init-srat/run
+++ b/sambanas2/rootfs/etc/s6-overlay/s6-rc.d/init-srat/run
@@ -7,71 +7,41 @@
 
 PRERELEASE_TAG=$(curl -s https://api.github.com/repos/dianlight/srat/releases | jq -r 'map(select(.prerelease)) | .[0].tag_name')
 RELEASE_TAG=$(curl -s https://api.github.com/repos/dianlight/srat/releases | jq -r 'map(select(.release)) | .[0].tag_name')
-tmp_file_cli=$(mktemp -u -t srat-cli.XXXXXX)
-tmp_file_server=$(mktemp -u -t srat-server.XXXXXX)
+tmp_dir=$(mktemp -d -t srat.XXXXXX)
+BASE_URL=https://github.com/dianlight/srat/releases/download/
+ZIP_NAME=srat_${BUILD_ARCH}.zip
+DOWNLOAD_URL=http://local_addon_registry.home:8090/
 
 if bashio::config.has_value 'update_srat_onstart'; then
   bashio::log.info "Update on start: $(bashio::config 'update_srat_onstart')"
   if bashio::config.equals 'update_srat_onstart' 'release'; then
     bashio::log.info "Updating to ${RELEASE_TAG}"
-    bashio::log.debug "Downloading from https://github.com/dianlight/srat/releases/download/${RELEASE_TAG}/srat-[cli|server]_$(arch)"  
-    if ! curl --silent --fail -L "https://github.com/dianlight/srat/releases/download/${RELEASE_TAG}/srat-cli_$(arch)" >$tmp_file_cli; then
+    if ! curl --silent --fail -L "${BASE_URL}${RELEASE_TAG}/${ZIP_NAME}" | unzip - -d $tmp_dir; then
       bashio::log.error "Failed to download srat release from github"
     fi
-    if ! curl --silent --fail -L "https://github.com/dianlight/srat/releases/download/${RELEASE_TAG}/srat-server_$(arch)" >$tmp_file_server; then
-      bashio::log.error "Failed to download srat release from github"
-    fi
-    #gh -R dianlight/srat release download $RELEASE_TAG -p "srat_$(arch)" -O /usr/local/bin/srat --clobber
   elif bashio::config.equals 'update_srat_onstart' 'prerelease'; then
     bashio::log.info "Updating to ${PRERELEASE_TAG}"
-    bashio::log.debug "Downloading from https://github.com/dianlight/srat/releases/download/${PRERELEASE_TAG}/srat-[cli|server]_$(arch)"  
-    if ! curl --silent --fail -L "https://github.com/dianlight/srat/releases/download/${PRERELEASE_TAG}/srat-cli_$(arch)" >$tmp_file_cli; then
-      bashio::log.error "Failed to download srat prerelease from github"
+    if ! curl --silent --fail -L "${BASE_URL}${PRERELEASE_TAG}/${ZIP_NAME}" | unzip - -d $tmp_dir; then
+      bashio::log.error "Failed to download srat release from github"
     fi
-    if ! curl --silent --fail -L "https://github.com/dianlight/srat/releases/download/${PRERELEASE_TAG}/srat-server_$(arch)" >$tmp_file_server; then
-      bashio::log.error "Failed to download srat prerelease from github"
-    fi
-    #gh -R dianlight/srat release download $PRERELEASE_TAG -p "srat_$(arch)" -O /usr/local/bin/srat --clobber
-  elif bashio::config.equals 'update_srat_onstart' 'localdev'; then    
+  elif bashio::config.equals 'update_srat_onstart' 'localdev'; then
     bashio::log.info "Updating to from local_addon_registry.home repository"
-    bashio::log.debug "Downloading from local_addon_registry.home repository"  
-    if ! curl --silent --fail -L "http://local_addon_registry.home:8090/srat-cli_$(arch)" >$tmp_file_cli; then
-      bashio::log.error "Failed to download srat from local_addon_registry.home"
-      if [ -f /config/srat-cli_$(arch) ]; then
-        bashio::log.info "Using existing srat from /config/srat-cli_$(arch)"
-        tmp_file_cli=/config/srat-cli_$(arch)
-      else
-        bashio::log.error "Failed to download srat from local_addon_registry.home and no existing srat-cli_$(arch) found"
-      fi
+    if ! curl --silent --fail -L "http://local_addon_registry.home:8090/${ZIP_NAME}" | unzip - -d $tmp_dir; then
+      bashio::log.error "Failed to download srat release from github"
     fi
-    if ! curl --silent --fail -L "http://local_addon_registry.home:8090/srat-server_$(arch)" >$tmp_file_server; then
-      bashio::log.error "Failed to download srat from local_addon_registry.home"
-      if [ -f /config/srat-server_$(arch) ]; then
-        bashio::log.info "Using existing srat from /config/srat-server_$(arch)"
-        tmp_file_server=/config/srat-server_$(arch)
-      else
-        bashio::log.error "Failed to download srat from local_addon_registry.home and no existing srat-server_$(arch) found"
-      fi
+  elif bashio::config.equals 'update_srat_onstart' 'localfile'; then
+    bashio::log.info "Updating to from local_addon_registry.home repository"
+    if [ -f /config/srat-cli_$(arch) ]; then
+      bashio::log.info "Using existing srat from /config/srat-cli_$(arch)"
+      mv -v /config/srat* $tmp_dir
+    else
+      bashio::log.error "No update found"
     fi
   fi
-
-  if [ -f $tmp_file_cli ]; then
-    bashio::log.info "Installing $tmp_file_cli to /usr/local/bin/srat-cli"
-    cp -v $tmp_file_cli /usr/local/bin/srat-cli
-    chmod +x /usr/local/bin/srat-cli
-  else
-    bashio::log.error "Failed to download srat from github"
-  fi
-  if [ -f $tmp_file_server ]; then
-    bashio::log.info "Installing $tmp_file_server to /usr/local/bin/srat-server"
-    cp -v $tmp_file_server /usr/local/bin/srat-server
-    chmod +x /usr/local/bin/srat-server
-  else
-    bashio::log.error "Failed to download srat from github"
-  fi
+  find $tmp_dir -name "srat*" -exec echo "Installing {} to /usr/local/bin/" -exec mv -v {} /usr/local/bin/ \;
 fi
 
-ls -al /usr/local/bin/srat* 
+ls -al /usr/local/bin/srat*
 
 /usr/local/bin/srat-cli \
   -db /config/config.db3 \
@@ -83,5 +53,4 @@ ls -al /usr/local/bin/srat*
   -docker-network "$(bashio::network 'network.info.docker.network' '.docker.address')" \
   2>&1
 
- bashio::log.info "srat-cli ok"
-
+bashio::log.info "srat-cli ok"
