Fix [SambaNas] Autmount error if reference an hassos disk #124

diff --git a/sambanas/rootfs/etc/s6-overlay/s6-rc.d/init-automount/run b/sambanas/rootfs/etc/s6-overlay/s6-rc.d/init-automount/run
--- a/sambanas/rootfs/etc/s6-overlay/s6-rc.d/init-automount/run
+++ b/sambanas/rootfs/etc/s6-overlay/s6-rc.d/init-automount/run
@@ -11,20 +11,30 @@ declare interface
 declare ipaddress
 declare ssh_private_key
 declare remote_mount
-declare devpath
 declare fstypes
+declare dev
 
 function disk2label() { # $1 disk  return (label disk or id)
      local disk=$1
      if [[ $disk == id:* ]]; then
           disk=${disk:3}
-          label=$(lsblk -no label /dev/disk/by-id/$disk)
-          if [[ ! -z "$label" && -L "/dev/disk/by-label/$label" ]]; then
-               bashio::log.info "Disk with id ${disk} is labeled $label so $label is used."
-               disk="$label"
+          if [ -L /dev/disk/by-id/$disk ]; then
+               label=$(lsblk -no label /dev/disk/by-id/$disk)
+               if [[ ! -z "$label" && -L "/dev/disk/by-label/$label" ]]; then
+                    bashio::log.info "Disk with id ${disk} is labeled $label so $label is used."
+                    disk="$label"
+               else
+                    disk=$1
+               fi
           else
-               disk=$1
+               bashio::log.warning "Disk with id ${disk} not found."
+               return 1
           fi
+     else
+          blkid -L "$disk" >>/dev/null || {
+               bashio::log.warning "Disk with label ${disk} not found."
+               return 1
+          }
      fi
      echo $disk
      return 0
@@ -35,11 +45,21 @@ function mount_disk() { # $1 disk $2 path $3 remote_mount
      disk=$1
      path=$2
      remote_mount=$3
-     devpath=/dev/disk/by-label
      if [[ $disk == id:* ]]; then
           bashio::log.debug "Disk ${disk:3} is an ID"
-          devpath=/dev/disk/by-id
-          disk=${disk:3}
+          dev=/dev/disk/by-id/${disk:3}
+          if [ -L $dev ]; then
+               disk=${disk:3}
+          else
+               unset dev
+          fi
+     else
+          dev=$(blkid -L "$disk")
+     fi
+
+     if [ -z $dev ]; then
+          bashio::log.info "Disk ${disk} not found! <SKIP>"
+          return 0
      fi
 
      mdisk=$(printf %b "$disk")
@@ -54,7 +74,7 @@ function mount_disk() { # $1 disk $2 path $3 remote_mount
           return 0
      else
           # Check FS type and set relative options
-          fstype=$(lsblk "$devpath/$disk" -no fstype)
+          fstype=$(lsblk $dev -no fstype)
           options="nosuid,relatime,noexec"
           type="auto"
           case "$fstype" in
@@ -73,10 +93,10 @@ function mount_disk() { # $1 disk $2 path $3 remote_mount
           esac
 
           if [ "$remote_mount" = true ]; then
-               ssh root@${ipaddress%/*} -p 22222 -o "StrictHostKeyChecking no" "if findmnt '/mnt/data/supervisor/media/$mdisk ' >/dev/null; then echo 'Disk $mdisk already mounted on host' ; else  mount -t $type '$devpath/$disk' '/mnt/data/supervisor/media/$mdisk' -o $options; fi" &&
-                    echo $devpath/$disk >>/tmp/remote_mount
+               ssh root@${ipaddress%/*} -p 22222 -o "StrictHostKeyChecking no" "if findmnt '/mnt/data/supervisor/media/$mdisk ' >/dev/null; then echo 'Disk $mdisk already mounted on host' ; else  mount -t $type '$dev' '/mnt/data/supervisor/media/$mdisk' -o $options; fi" &&
+                    echo $dev >>/tmp/remote_mount
           fi || bashio::log.warning "Host Mount ${mdisk}[${fstype}] Fail!" || :
-          mount -t $type "$devpath/$disk" "$path/$mdisk" -o $options &&
+          mount -t $type "$dev" "$path/$mdisk" -o $options &&
                echo $path/$mdisk >>/tmp/local_mount && bashio::log.info "Mount ${mdisk}[${fstype}] Success!"
      fi
 }
@@ -130,31 +150,38 @@ elif bashio::config.has_value 'moredisks' || bashio::config.true 'automount'; th
           bashio::log.info "MediaLibrary disabled in config. Disk are mounted only for this addon!"
      fi
 
+     OIFS=$IFS
+     IFS=$'\n'
+
      ## List available Disk with Labels and Id
      if bashio::config.true 'available_disks_log' || bashio::config.true 'automount'; then
           bashio::log.blue "---------------------------------------------------"
-          autodisks=($(ls /dev/disk/by-label | grep -v hassos))
+          #autodisks=($(lsblk -E label -n -o label | sed -r '/^\s*$/d' | grep -v hassos | grep pp))
+          readarray -t autodisks < <(lsblk -E label -n -o label -i | sed -r '/^\s*$/d' | grep -v hassos)
           if [ ${#autodisks[@]} -eq 0 ]; then
                bashio::log.info "No Disk with labels."
           else
                bashio::log.info "Available Disk Labels:"
                for disk in ${autodisks[@]}; do
-                    bashio::log.info "\t${disk}[$(lsblk /dev/disk/by-label/$disk -no fstype)]"
+                    bashio::log.info "\t${disk}[$(lsblk $(blkid -L "$disk") -no fstype)]"
                done
           fi
           bashio::log.blue "---------------------------------------------------"
      fi
 
-     OIFS=$IFS
-     IFS=$'\n'
      moredisks=($(bashio::config 'moredisks'))
      if [ ${#moredisks[@]} -eq 0 ]; then
           bashio::log.info "No MoreDisks to mount"
      else
           bashio::log.info "MoreDisks to mount:\n" $(printf "\t%s\n" "${moredisks[@]}")
+          i=0
+          mmoredisks=()
           for index in "${!moredisks[@]}"; do
-               moredisks[$index]=$(disk2label "${moredisks[$index]}")
+               tmpd=$(disk2label "${moredisks[$index]}") &&
+                    mmoredisks[$i]=$tmpd &&
+                    ((i = i + 1))
           done
+          moredisks=("${mmoredisks[@]}")
      fi
 
      if bashio::config.true 'automount' && [ ${#autodisks[@]} -gt 0 ]; then
@@ -165,7 +192,7 @@ elif bashio::config.has_value 'moredisks' || bashio::config.true 'automount'; th
           tomountdisks=("${moredisks[@]}")
      fi
 
-     if [ ${#moredisks[@]} -gt 0 ]; then
+     if [ ${#tomountdisks[@]} -gt 0 ]; then
           bashio::log.magenta "---------------------------------------------------"
           bashio::log.info "Mounting disks:\n" $(printf "\t%s\n" "${tomountdisks[@]}")
           bashio::log.magenta "---------------------------------------------------"
