exFat teste, space tested, mqtt tested

diff --git a/sambanas/rootfs/etc/s6-overlay/s6-rc.d/init-automount/run b/sambanas/rootfs/etc/s6-overlay/s6-rc.d/init-automount/run
--- a/sambanas/rootfs/etc/s6-overlay/s6-rc.d/init-automount/run
+++ b/sambanas/rootfs/etc/s6-overlay/s6-rc.d/init-automount/run
@@ -26,13 +26,15 @@ function mount_disk() { # $1 disk $2 path $3 remote_mount
           disk=${disk:3}
      fi
 
-     mkdir -p "$path/$disk"
-     chmod a+rwx "$path/$disk"
+     mdisk=$(printf %b "$disk")
+
+     mkdir -p "$path/$mdisk"
+     chmod a+rwx "$path/$mdisk"
 
      # check with findmnt if the disk is already mounted
-     if findmnt -n -o TARGET "$path/$disk" >/dev/null 2>&1; then
-          bashio::log.info "Disk ${disk} is already mounted"
-          echo $path/$disk >>/tmp/local_mount
+     if findmnt -n -o TARGET "$path/$mdisk" >/dev/null 2>&1; then
+          bashio::log.info "Disk ${mdisk} is already mounted"
+          echo $path/$mdisk >>/tmp/local_mount
           return 0
      else
           # Check FS type and set relative options
@@ -40,26 +42,26 @@ function mount_disk() { # $1 disk $2 path $3 remote_mount
           options="nosuid,relatime,noexec"
           type="auto"
           case "$fstype" in
-          exfat)
-               bashio::log.warning "Your ${disk} is based on FUSE exFat fs. Permissions and ACL don't works and This is an EXPERIMENTAL feature"
+          exfat | vfat | msdos)
+               bashio::log.warning "Your ${mdisk} as ${fstype} exFat. Permissions and ACL don't works and This is an EXPERIMENTAL feature"
                options="${options},umask=000"
                ;;
           ntfs)
-               bashio::log.warning "Your ${disk} is based on NTFS fs. This is an EXPERIMENTAL feature"
+               bashio::log.warning "Your ${mdisk} as fstype NTFS. This is an EXPERIMENTAL feature"
                options="${options},umask=000"
                type="ntfs3"
                ;;
           *)
-               bashio::log.info "Mounting ${disk} of type ${fstype}"
+               bashio::log.info "Mounting ${mdisk} of type ${fstype}"
                ;;
           esac
 
           if [ "$remote_mount" = true ]; then
-               ssh root@${ipaddress%/*} -p 22222 -o "StrictHostKeyChecking no" "if grep -qs '/mnt/data/supervisor/media/$disk ' /proc/mounts; then echo 'Disk $disk already mounted on host' ; else  mount -t $type '$devpath/$disk' '/mnt/data/supervisor/media/$disk' -o $options; fi" &&
+               ssh root@${ipaddress%/*} -p 22222 -o "StrictHostKeyChecking no" "if findmnt '/mnt/data/supervisor/media/$mdisk ' >/dev/null; then echo 'Disk $mdisk already mounted on host' ; else  mount -t $type '$devpath/$disk' '/mnt/data/supervisor/media/$mdisk' -o $options; fi" &&
                     echo $devpath/$disk >>/tmp/remote_mount
-          fi || bashio::log.warning "Host Mount ${disk}[${fstype}] Fail!" || :
-          mount -t $type "$devpath/$disk" "$path/$disk" -o $options &&
-               echo $path/$disk >>/tmp/local_mount && bashio::log.info "Mount ${disk}[${fstype}] Success!"
+          fi || bashio::log.warning "Host Mount ${mdisk}[${fstype}] Fail!" || :
+          mount -t $type "$devpath/$disk" "$path/$mdisk" -o $options &&
+               echo $path/$mdisk >>/tmp/local_mount && bashio::log.info "Mount ${mdisk}[${fstype}] Success!"
      fi
 }
 
@@ -72,11 +74,11 @@ elif bashio::config.has_value 'moredisks' || bashio::config.true 'automount'; th
      bashio::log.info "MoreDisk or Automount option found!"
 
      # Check supported FS
-     modprobe ntfs3
+     modprobe ntfs3 exfat
      fstypes=$(IFS=$'\n' echo $(cat /proc/filesystems | grep -v nodev))
      bashio::log.blue "---------------------------------------------------"
      bashio::log.green "Supported fs: ${fstypes}"
-     bashio::log.green "Supported fusefs: $(find /sbin -name "mount*fuse" | cut -c 13- | tr "\n" " " | sed s/fuse//g)"
+     if cat /proc/filesystems | grep -q fuseblk; then bashio::log.green "Supported fusefs: $(find /sbin -name "mount*fuse" | cut -c 13- | tr "\n" " " | sed s/fuse//g)"; fi
      bashio::log.blue "---------------------------------------------------"
 
      # Check Host Ssh config
