🐛 Update Samba NAS version to 12.5.0-nas.alpha20 and enhance SRAT update logic with error handling for downloads

diff --git a/sambanas/rootfs/etc/s6-overlay/s6-rc.d/srat/run b/sambanas/rootfs/etc/s6-overlay/s6-rc.d/srat/run
--- a/sambanas/rootfs/etc/s6-overlay/s6-rc.d/srat/run
+++ b/sambanas/rootfs/etc/s6-overlay/s6-rc.d/srat/run
@@ -7,36 +7,54 @@
 
 PRERELEASE_TAG=$(curl -s https://api.github.com/repos/dianlight/srat/releases | jq -r 'map(select(.prerelease)) | .[0].tag_name')
 RELEASE_TAG=$(curl -s https://api.github.com/repos/dianlight/srat/releases | jq -r 'map(select(.release)) | .[0].tag_name')
+tmp_file=$(mktemp -u -t srat.XXXXXX)
 
 if bashio::config.has_value 'update_srat_onstart'; then
   bashio::log.info "Update on start: $(bashio::config 'update_srat_onstart')"
   if bashio::config.equals 'update_srat_onstart' 'release'; then
     bashio::log.info "Updating to ${RELEASE_TAG}"
     bashio::log.debug "Downloading from https://github.com/dianlight/srat/releases/download/${RELEASE_TAG}/srat_$(arch)"  
-    curl -L "https://github.com/dianlight/srat/releases/download/${RELEASE_TAG}/srat_$(arch)" >/usr/local/bin/srat
+    if ! curl --silent --fail -L "https://github.com/dianlight/srat/releases/download/${RELEASE_TAG}/srat_$(arch)" >$tmp_file; then
+      bashio::log.error "Failed to download srat release from github"
+    fi
     #gh -R dianlight/srat release download $RELEASE_TAG -p "srat_$(arch)" -O /usr/local/bin/srat --clobber
   elif bashio::config.equals 'update_srat_onstart' 'prerelease'; then
     bashio::log.info "Updating to ${PRERELEASE_TAG}"
     bashio::log.debug "Downloading from https://github.com/dianlight/srat/releases/download/${PRERELEASE_TAG}/srat_$(arch)"  
-    curl -L "https://github.com/dianlight/srat/releases/download/${PRERELEASE_TAG}/srat_$(arch)" >/usr/local/bin/srat
+    if ! curl --silent --fail -L "https://github.com/dianlight/srat/releases/download/${PRERELEASE_TAG}/srat_$(arch)" >$tmp_file; then
+      bashio::log.error "Failed to download srat prerelease from github"
+    fi
     #gh -R dianlight/srat release download $PRERELEASE_TAG -p "srat_$(arch)" -O /usr/local/bin/srat --clobber
-  elif bashio::config.equals 'update_srat_onstart' 'localdev'; then
+  elif bashio::config.equals 'update_srat_onstart' 'localdev'; then    
     bashio::log.info "Updating to from local_addon_registry.home repository"
-    bashio::log.debug "Downloading from local_addon_registry.home repository"
-    curl -L "http://local_addon_registry.home:8090/srat_$(arch)" >/usr/local/bin/srat
+    bashio::log.debug "Downloading from local_addon_registry.home repository"  
+    if ! curl --silent --fail -L "http://local_addon_registry.home:8090/srat_$(arch)" >$tmp_file; then
+      bashio::log.error "Failed to download srat from local_addon_registry.home"
+      if [ -f /config/srat_$(arch) ]; then
+        bashio::log.info "Using existing srat from /config/srat_$(arch)"
+        tmp_file=/config/srat_$(arch)
+      else
+        bashio::log.error "Failed to download srat from local_addon_registry.home and no existing srat_$(arch) found"
+      fi
+    fi
   fi
-  chmod +x /usr/local/bin/srat
-fi
 
-# s6-svc -r /var/run/s6/services/<service name>
-# -addon \
+  if [ -f $tmp_file ]; then
+    bashio::log.info "Installing srat to /usr/local/bin/srat"
+    cp $tmp_file /usr/local/bin/srat
+    chmod +x /usr/local/bin/srat
+  else
+    bashio::log.error "Failed to download srat from github"
+  fi
+fi
 
 exec /usr/local/bin/srat \
   -port $(bashio::addon.ingress_port) \
   $(bashio::var.has_value "$(bashio::addon.port 3000)" || echo " -addon") \
   -conf /config/bootconfig.json \
-  -db /data/config.db3 \
+  -db /config/config.db3 \
   -out /etc/samba/smb.conf \
   -docker-interface "$(bashio::network 'network.info.docker.inerface' '.docker.interface')" \
-  -docker-network "$(bashio::network 'network.info.docker.network' '.docker.address')"
-
+  -docker-network "$(bashio::network 'network.info.docker.network' '.docker.address')" \
+  $(bashio::config.equals 'update_srat_onstart' 'localdev' && echo " -update-file-path /config/srat_$(arch)") \
+  -loglevel $(bashio::config 'loglevel' 'info')
